version: "3.8"
services:
    app:
        container_name: moto-store-app
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        volumes:
            - ./:/var/www/html
        depends_on:
            - db
        networks:
            - moto
    db:
        image: mysql
        container_name: moto-store-mysql
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: "example"
            MYSQL_PASSWORD: "example-root"
            MYSQL_ROOT_PASSWORD: "example-root"
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - moto
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: moto-store-phpmyadmin
        links:
            - db:db
        ports:
            - 8080:80
        environment:
            MYSQL_USER: "root"
            MYSQL_PASSWORD: "example-root"
            MYSQL_ROOT_PASSWORD: "example-root"
        networks:
            - moto
volumes:
    db_data:
networks:
    moto:
